### ISSUE TITLE
BUG: If finviz doesnt have ratings table ticker_full_info() fails

### ISSUE THREAD

**Issue by ranger9692** [lit26/finvizfinance#65] opened 2023-02-03 20:09 UTC
### finvizfinance version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the master branch of finvizfinance.

### Reproducible Example

```python
x = finvizfinance('acon')
x.ticker_full_info()
```

### Issue Description

Traceback (most recent call last):

  File "C:\Users\chris\AppData\Local\Temp\ipykernel_20800\477896250.py", line 1, in <module>
    x2 = x.ticker_full_info()

  File "C:\Users\chris\anaconda3\lib\site-packages\finvizfinance\quote.py", line 377, in ticker_full_info
    self.ticker_outer_ratings()

  File "C:\Users\chris\anaconda3\lib\site-packages\finvizfinance\quote.py", line 233, in ticker_outer_ratings
    rows = fullview_ratings_outer.findAll("td", class_="fullview-ratings-inner")

AttributeError: 'NoneType' object has no attribute 'findAll'

### Expected Behavior

I think you should have the results return with the ratings with an empty dataframe or a nonetype

### Installed Versions

<details>

(base) C:\Users\chris>pip show finvizfinance
Name: finvizfinance
Version: 0.14.4
Summary: Finviz Finance. Information downloader.
Home-page: https://github.com/lit26/finvizfinance
Author: Tianning Li
Author-email: ltianningli@gmail.com
License: The MIT License (MIT)
Location: c:\users\chris\anaconda3\lib\site-packages
Requires: bs4, datetime, lxml, pandas, requests
Required-by:

</details>

**Comment by tli26** [comment] 2023-02-03 20:18
It seems `ACON` has no outer rating. I will fix it.

**Comment by ranger9692** [comment] 2023-02-03 20:27
I really appreciate it.  Nice package.  Thanks for it.  -Chris

**Comment by ranger9692** [comment] 2023-02-03 20:29
Also, does the library give the Income Statement, Balance sheet and Cash
Flow?  Annual and quarterly?

**Comment by tli26** [comment] 2023-02-03 20:31
Yup, https://finvizfinance.readthedocs.io/en/latest/quote.html#finvizfinance.quote.Statements

**Comment by lit26** [comment] 2023-02-04 03:32
The issue is fixed in the latest version. Please upgrade your package.

**Closed by lit26** 2023-02-04 03:32 UTC

**Comment by ranger9692** [comment] 2023-02-07 14:42
Thanks for the update.  Im wondering if your package works behind the
paywall of finviz if you have a username and password?  I was hoping to
grab the groups/industry performance results premarket but it returns last
nights results until after open.

**Comment by lit26** [comment] 2023-02-09 21:17
Currently, I am not planning to do that but looking for contribution on this.
